### ISSUE TITLE
Stops server from loading

### ISSUE THREAD

**Issue by NonniT** [Trcx528/Swapper#1]
Great work! But, for some reason it stops my (modified) Infinity server from loading. Could be a conflict with another mod somewhere of some sort; I'm not sure what's up as I'm not a programmer of any kind! It didn't impact the client at all for some reason. Figured you'd appreciate the crash report though :)

http://pastebin.com/3Ruji8HZ

**Comment by Trcx528** [comment]
look for the 1.0.2 download, hopefully should fix the bug :) reopen the ticket if it doesn't/
