### ISSUE TITLE
Corrupts a world

### ISSUE THREAD

**Issue by xyosei** [Trcx528/Swapper#10]
Whenever you put a TiCon crossbow in the Right Click slot and the arrows in another Right Click slot in a different Swapper it will corrupt the world.

**Comment by Trcx528** [comment]
Offhand I'm not sure why this would be.  What do you mean by it corrupts the world? Does the world not load anymore? Does it revert back chunks?  Some more details would be appreciated.  

The short term (and potentially long term) fix would be to add either the cross bow or the arrows/bolts into the swapper blacklist in the configuration file.  I will do my best to investigate this quickly, but I'm very busy in real life at the moment.

**Comment by xyosei** [comment]
Well, the world will not load. at all. i had to uninstall your mod in order to make my world playable again. It's an amazing mod and i want to play with it really bad because it has so much potential, but it is a little buggy right now, but it's to be expected because its a new mod.

**Comment by xyosei** [comment]
I have two theories on why this wouldnt work, feel free to correct me if im wrong. One, the swapper doesnt want to support the animation of the crossbow being drawn back. Two, the swapper doesnt want to coperate with the arrows being pulled from outside of the swapper, or with the crossbow trying to draw something from outside the swapper. Or possibly a combination of the two.

**Comment by Trcx528** [comment]
Is there any chance that you have your original world file and/or player data? I'd like to take a look at it.  I have tried numerous ways to reproduce this issue but haven not been able to.  

I seriously doubt that swapper is responsible for your world not loading.  It does nothing more than read and write a small amount of nbt data to an item in your inventory using code borrowed from openmods lib, which has been very well tested and works reliably.  

I am aware that swapper does not work with a number of the right click items from tcon.  It's something that I've been looking into fixing/adding but have not been able to figure out the "trick" to it yet.  Regardless of the animations it should not corrupt you world, at the most I've see is a client crash.  The arrows in a second swapper are irrelevant.  The crossbow looks through all the slots of your inventory and checks to see if the slot is an arrow (in this case it would only see the swapper), there is no way that it could find an arrow in the swapper without me doing something special (which I have not done).

**Comment by Trcx528** [comment]
Also could you provide a mod list and any more relevant details about what you were doing before you logged out and couldn't open the world back up?

**Comment by Trcx528** [comment]
I am going to close this issue due to a lack of response and because I have been unable to reproduce it.  If someone else encounters a world corruption bug please reopen this ticket with more specific details.
