### ISSUE TITLE
Switch to axe for livingwood

### ISSUE THREAD

**Issue by gazpachoking** [Trcx528/Swapper#4]
Minecraft: 1.7.10
Forge: 10.13.2.1291
Swapper: 1.0.2
Botania: r1.5-165
It seems that it switches to a pickaxe when trying to harvest livingwood (from botania) rather than the axe. WAILA is properly reporting that the effective tool is an axe, not sure if you are pulling info the same way as that mod.

**Comment by Trcx528** [comment]
Hmm looking at the walia harvestability source it looks like they have a better algorithm for detecting the block type. I'll update to use a similar sometime tomorrow.

**Comment by gazpachoking** [comment]
Awesome!
