### ISSUE TITLE
Tool Deletion/Dupe

### ISSUE THREAD

**Issue by Thiana** [Trcx528/Swapper#5]
Somehow Swapper 1.03 has duplicated my Lumber Axe and overwritten my Hammer. The tools in the screenshot are (Iguana) Tinkers (Excavator, LAxe, LAxe), Draconic Evolution Sword and Reliquary Soujourner's Staff.

I'm really glad I had a backup of my tools in a creative chest ;)

The modpack is basically FTB Infinity 1.3.1 with some mods (IC2, iChun's and Headcrumbs) removed and a few added (Reliquary, Iron Backpacks, Iguana Tinker Tweaks, Compact Machines)

Thanks.

![2015-03-19_14 16 29](https://cloud.githubusercontent.com/assets/405832/6737579/da65f3f2-ce42-11e4-9981-85e8c94858fc.png)

**Comment by Thiana** [comment]
The modpack is basically FTB Infinity with some mods (IC2, iChun's and Headcrumbs) removed and a few added (Reliquary, Iron Backpacks, Iguana Tinker Tweaks, Compact Machines)

**Comment by Trcx528** [comment]
Do you know what you did to cause this?  What are the steps to reproduce?

**Comment by Thiana** [comment]
Unfortunately not. I only noticed it when I tried to remove the ineffable glass in the screenshot and it only removed a single block instead of all 6. I've reset the swapper to the original tools and I'll try and isolate some sort of cause.

**Comment by Trcx528** [comment]
With any luck this'll prevent this bug from happening again.  Watch for the new version and please reopen this ticket if it happens again.
