### ISSUE TITLE
Sword Enhancement

### ISSUE THREAD

**Issue by gazpachoking** [Trcx528/Swapper#6]
I like how this system works quite a bit, one small issue I have is tools swapping too fast when I mean to use the sword. I was fighting an enderminy, and every time I missed my sword swing by a little bit I was digging a deeper and deeper hole in the ground because it would pull out my shovel. Perhaps the sword could be a little bit 'sticky'? Like maybe after hitting a mob, there is a half second cooldown before it will automatically switch away from the sword or something like that. Or maybe it's just not a good plan for me to combine my sword in the swapper with all my super efficient tools.

**Comment by Trcx528** [comment]
I'll see what I can do to make this happen.  Might be a little tricky but I'll try.

**Comment by Trcx528** [comment]
Fixed in the next update.
