### ISSUE TITLE
TiCon rendering issue with IguanaTweaks 2.1.2

### ISSUE THREAD

**Issue by chouje** [Trcx528/Swapper#7]
In FTB Infinity 1.3.1 with IguanaTweaks 2.1.2 added, Tinker's Construct tools inside the Swapper do not render at all - only the damage bar is shown (see screenshot). Other vanilla or mod tools seem to render fine (tested with a Stone and a Thaumium Sword).
![ticon](https://cloud.githubusercontent.com/assets/11563125/6742264/a2b6497e-ce8e-11e4-8cee-ca7c6ce8e268.png)

P.S. This mod is the best thing since sliced bread, thanks!

**Comment by Trcx528** [comment]
I'll have to look into this.  Does the tool render in your hand? 

Also does the swapper flicker in your hand? There is a mod that causes flicking in popular mod packs but I haven't been able to narrow down which one yet.

**Comment by chouje** [comment]
Nope, no flickering, and the tool renders fine in the hand.
