### ISSUE TITLE
Manual Swapper?

### ISSUE THREAD

**Issue by gazpachoking** [Trcx528/Swapper#9]
Was thinking it might be cool to add a manual swapper (maybe 'tool belt' is a more approprate name) as well, that allowed any tools, and switched between tools with shift+scrollwheel (similar to enderio wrench modes.) My use case would be to have stuff like a wrench, carpenter's hammer, wand of the forest, and chisel all available on my hotbar when needed without taking up too much space. Might be out of scope for this mod, but figured I'd suggest it anyway.

**Comment by Trcx528** [comment]
I'll continue to think about it my initial reaction is that it's outside the scope.  Maybe if I find myself with some time in the future I'll add it, but probably not.
